### ISSUE TITLE
Generator scripts are out of date

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#154]
The generator scripts are out of date and need to be reviewed. Notably the following needs to be addressed:

- [ ] Div/TrueDiv changes ( #130)
- [ ] Exec and backquotes (#133)
- [ ] OldInstance, nonlocal and async (#141)

Would be nice if the code was Python 3 compatible as well...

**Comment by slide** [comment]
I thought I already ran 2to3 on them.
